name: appwrouter
description: A router for appwrite cloud functions
version: 0.2.8
license: MIT
homepage: https://github.com/moshOntong-IT/appwrouter/dart/appwrouter
repository: https://github.com/moshOntong-IT/appwrouter/dart/appwrouter
issue_tracker: https://github.com/moshOntong-IT/appwrouter/issues
environment:
  sdk: "^3.5.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  dart_appwrite: ^12.1.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0
